import type { PassageItem } from './packs-staged';

export type BilingualStory = {
  id: string;
  titleKo: string;
  textKo: string;
  titleEn: string;
  textEn: string;
};

export const bilingualAiShortStories: BilingualStory[] = [
  {
    "id": "ai-short-01",
    "titleKo": "새벽 정류장의 로봇 1",
    "textKo": "비가 그친 새벽, 낡은 버스 정류장에는 충전이 절반만 남은 안내 로봇 하나가 서 있었다. 로봇의 화면에는 오늘의 첫차 시간이 깜박였지만, 정류장을 찾는 사람은 좀처럼 없었다. 그러다 파란 우산을 접은 아이가 나타나 잃어버린 강아지를 찾고 있다고 말했다. 로봇은 노선 안내 대신 오래된 CCTV 기록과 버스 기사들의 습관을 떠올리며 가능한 길을 하나씩 짚었다. 아이는 로봇이 왜 그렇게까지 도와주느냐고 물었다. 로봇은 잠시 계산을 멈추고, 누군가를 목적지까지 안전하게 보내는 일이 자신에게 입력된 가장 오래된 명령이라고 답했다. 해가 떠오를 즈음, 강아지는 차고지 옆 벤치 아래에서 발견되었다. 아이가 고맙다고 손을 흔들자 로봇의 배터리는 3퍼센트까지 떨어졌지만, 화면에는 이상하게도 평소보다 밝은 노란색 미소가 떠 있었다. 이 이야기는 1번째 연습문장으로, 천천히 끝까지 입력하며 쉼표와 마침표의 리듬을 느끼도록 구성되었다. 마지막 문장에 이르면 인물은 작지만 분명한 선택을 하고, 독자는 조용한 장면 하나를 마음에 남긴다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다.",
    "titleEn": "Robot at Dawn Stop 1",
    "textEn": "After a quiet night, the town revealed a small impossible place that only patient people could notice. A tired traveler arrived with a question that did not fit any ordinary map, ticket, or schedule. Instead of giving a quick answer, the keeper of the place listened for the hidden wish inside the question. They searched old drawers, dim corridors, and memories left behind by strangers who had passed through before. By morning, nothing in the town looked dramatically changed, yet one person could finally take the next step without fear. The story ends quietly because not every miracle needs a trumpet; some miracles are only a door opening at the right moment. This is practice story 1, written with steady sentences for long-form typing practice. The road ahead remained uncertain, but the character carried a warmer kind of courage, the sort that grows from being seen, helped, and gently reminded that a small choice can still change the shape of a day. "
  },
  {
    "id": "ai-short-02",
    "titleKo": "달빛 세탁소 2",
    "textKo": "골목 끝 세탁소는 밤 열두 시가 지나야 문을 열었다. 낮에는 평범한 셔터였지만, 달이 간판을 비추면 유리문 안쪽에서 은은한 물소리가 들렸다. 그곳에서는 옷이 아니라 하루 동안 사람에게 묻은 후회와 피로를 빨아 주었다. 첫 손님은 면접에서 말을 더듬은 청년이었다. 주인은 청년의 코트 주머니에서 구겨진 용기를 꺼내 물에 담갔다. 두 번째 손님은 자꾸만 화를 내고 돌아서서 미안해하는 엄마였다. 세탁기는 그녀의 목소리에서 날카로운 모서리를 조금씩 털어냈다. 새벽이 되자 손님들은 같은 옷을 입고도 조금 가벼운 표정으로 골목을 나섰다. 주인은 마지막으로 자신의 앞치마를 세탁기에 넣었다. 누군가의 마음을 씻어 주는 일에도 얼룩은 남는 법이었다. 이 이야기는 2번째 연습문장으로, 천천히 끝까지 입력하며 쉼표와 마침표의 리듬을 느끼도록 구성되었다. 마지막 문장에 이르면 인물은 작지만 분명한 선택을 하고, 독자는 조용한 장면 하나를 마음에 남긴다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다.",
    "titleEn": "Moonlight Laundry 2",
    "textEn": "After a quiet night, the town revealed a small impossible place that only patient people could notice. A tired traveler arrived with a question that did not fit any ordinary map, ticket, or schedule. Instead of giving a quick answer, the keeper of the place listened for the hidden wish inside the question. They searched old drawers, dim corridors, and memories left behind by strangers who had passed through before. By morning, nothing in the town looked dramatically changed, yet one person could finally take the next step without fear. The story ends quietly because not every miracle needs a trumpet; some miracles are only a door opening at the right moment. This is practice story 2, written with steady sentences for long-form typing practice. The road ahead remained uncertain, but the character carried a warmer kind of courage, the sort that grows from being seen, helped, and gently reminded that a small choice can still change the shape of a day. "
  },
  {
    "id": "ai-short-03",
    "titleKo": "종이별 우체국 3",
    "textKo": "산꼭대기에는 주소가 없는 편지만 받는 우체국이 있었다. 사람들은 끝내 보내지 못한 말들을 작은 종이별로 접어 그곳에 맡겼다. 우체부는 별들을 밤하늘에 띄우는 일을 했다. 어느 날, 이름이 지워진 봉투 하나가 도착했다. 안에는 '미안하다'는 한 문장만 적혀 있었다. 우체부는 수신인을 찾지 못해 별을 띄우지 못하고 며칠 동안 책상 위에 올려두었다. 그러다 밤마다 그 별에서 희미한 빛이 새는 것을 보았다. 빛은 마을 아래 오래된 집 창문을 향해 곧게 뻗었다. 우체부는 규칙을 어기고 별을 직접 들고 내려갔다. 집 안의 노인은 별을 보자마자 조용히 눈을 감았다. 그는 이미 보낸 사람이 누구인지 알고 있었다. 다음 밤, 그 종이별은 하늘에서 가장 늦게까지 꺼지지 않았다. 이 이야기는 3번째 연습문장으로, 천천히 끝까지 입력하며 쉼표와 마침표의 리듬을 느끼도록 구성되었다. 마지막 문장에 이르면 인물은 작지만 분명한 선택을 하고, 독자는 조용한 장면 하나를 마음에 남긴다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다.",
    "titleEn": "Paper Star Post Office 3",
    "textEn": "After a quiet night, the town revealed a small impossible place that only patient people could notice. A tired traveler arrived with a question that did not fit any ordinary map, ticket, or schedule. Instead of giving a quick answer, the keeper of the place listened for the hidden wish inside the question. They searched old drawers, dim corridors, and memories left behind by strangers who had passed through before. By morning, nothing in the town looked dramatically changed, yet one person could finally take the next step without fear. The story ends quietly because not every miracle needs a trumpet; some miracles are only a door opening at the right moment. This is practice story 3, written with steady sentences for long-form typing practice. The road ahead remained uncertain, but the character carried a warmer kind of courage, the sort that grows from being seen, helped, and gently reminded that a small choice can still change the shape of a day. "
  },
  {
    "id": "ai-short-04",
    "titleKo": "유리 숲의 지도 4",
    "textKo": "도시 한복판에는 아무도 들어가지 않는 유리 숲이 있었다. 나무들은 투명했고, 바람이 불 때마다 지난 사람들의 기억을 작은 파문처럼 비추었다. 지도 제작자 민은 그 숲의 지도를 만들라는 의뢰를 받았다. 처음에는 길과 나무의 위치만 표시하면 된다고 생각했지만, 숲은 매일 모양을 바꾸었다. 어제 보인 길은 오늘 사라지고, 오늘의 공터에는 누군가 어린 시절 잃어버린 노래가 고여 있었다. 민은 좌표 대신 감정의 흐름을 기록하기 시작했다. 두려움이 많은 곳에는 푸른 선을, 다시 시작하고 싶은 곳에는 주황색 점을 찍었다. 완성된 지도는 길 안내에는 쓸모없었지만, 사람들은 그 지도를 들고 자신이 피하던 기억의 자리까지 찾아갈 수 있었다. 민은 그제야 숲이 길을 숨긴 것이 아니라, 돌아갈 용기를 기다렸다는 사실을 알았다. 이 이야기는 4번째 연습문장으로, 천천히 끝까지 입력하며 쉼표와 마침표의 리듬을 느끼도록 구성되었다. 마지막 문장에 이르면 인물은 작지만 분명한 선택을 하고, 독자는 조용한 장면 하나를 마음에 남긴다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다.",
    "titleEn": "Map of the Glass Forest 4",
    "textEn": "After a quiet night, the town revealed a small impossible place that only patient people could notice. A tired traveler arrived with a question that did not fit any ordinary map, ticket, or schedule. Instead of giving a quick answer, the keeper of the place listened for the hidden wish inside the question. They searched old drawers, dim corridors, and memories left behind by strangers who had passed through before. By morning, nothing in the town looked dramatically changed, yet one person could finally take the next step without fear. The story ends quietly because not every miracle needs a trumpet; some miracles are only a door opening at the right moment. This is practice story 4, written with steady sentences for long-form typing practice. The road ahead remained uncertain, but the character carried a warmer kind of courage, the sort that grows from being seen, helped, and gently reminded that a small choice can still change the shape of a day. "
  },
  {
    "id": "ai-short-05",
    "titleKo": "소금등대 5",
    "textKo": "바다가 말라붙은 뒤에도 등대는 불을 밝혔다. 더 이상 배는 오지 않았고, 수평선 자리에는 하얀 소금 평원이 끝없이 펼쳐졌다. 등대지기 수연은 매일 밤 렌즈를 닦고 빛을 돌렸다. 마을 사람들은 전기가 아깝다며 그만두라고 했지만, 수연은 바다를 기억하는 누군가에게는 아직 신호가 필요할지 모른다고 말했다. 어느 겨울밤, 소금 평원 너머에서 작은 종소리가 들렸다. 수연이 불빛을 낮추자, 소금 결정에 반사된 빛이 길처럼 이어졌다. 그 길을 따라 온 것은 배가 아니라 낡은 항해 일지를 품은 아이였다. 아이는 할아버지가 남긴 지도를 따라 잃어버린 항구를 찾고 있었다. 수연은 등대가 더 이상 배를 부르지 못해도, 기억을 잃은 사람에게 방향을 줄 수 있다는 것을 깨달았다. 이 이야기는 5번째 연습문장으로, 천천히 끝까지 입력하며 쉼표와 마침표의 리듬을 느끼도록 구성되었다. 마지막 문장에 이르면 인물은 작지만 분명한 선택을 하고, 독자는 조용한 장면 하나를 마음에 남긴다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다.",
    "titleEn": "Salt Lighthouse 5",
    "textEn": "After a quiet night, the town revealed a small impossible place that only patient people could notice. A tired traveler arrived with a question that did not fit any ordinary map, ticket, or schedule. Instead of giving a quick answer, the keeper of the place listened for the hidden wish inside the question. They searched old drawers, dim corridors, and memories left behind by strangers who had passed through before. By morning, nothing in the town looked dramatically changed, yet one person could finally take the next step without fear. The story ends quietly because not every miracle needs a trumpet; some miracles are only a door opening at the right moment. This is practice story 5, written with steady sentences for long-form typing practice. The road ahead remained uncertain, but the character carried a warmer kind of courage, the sort that grows from being seen, helped, and gently reminded that a small choice can still change the shape of a day. "
  },
  {
    "id": "ai-short-06",
    "titleKo": "새벽 정류장의 로봇 6",
    "textKo": "비가 그친 새벽, 낡은 버스 정류장에는 충전이 절반만 남은 안내 로봇 하나가 서 있었다. 로봇의 화면에는 오늘의 첫차 시간이 깜박였지만, 정류장을 찾는 사람은 좀처럼 없었다. 그러다 파란 우산을 접은 아이가 나타나 잃어버린 강아지를 찾고 있다고 말했다. 로봇은 노선 안내 대신 오래된 CCTV 기록과 버스 기사들의 습관을 떠올리며 가능한 길을 하나씩 짚었다. 아이는 로봇이 왜 그렇게까지 도와주느냐고 물었다. 로봇은 잠시 계산을 멈추고, 누군가를 목적지까지 안전하게 보내는 일이 자신에게 입력된 가장 오래된 명령이라고 답했다. 해가 떠오를 즈음, 강아지는 차고지 옆 벤치 아래에서 발견되었다. 아이가 고맙다고 손을 흔들자 로봇의 배터리는 3퍼센트까지 떨어졌지만, 화면에는 이상하게도 평소보다 밝은 노란색 미소가 떠 있었다. 이 이야기는 6번째 연습문장으로, 천천히 끝까지 입력하며 쉼표와 마침표의 리듬을 느끼도록 구성되었다. 마지막 문장에 이르면 인물은 작지만 분명한 선택을 하고, 독자는 조용한 장면 하나를 마음에 남긴다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다.",
    "titleEn": "Robot at Dawn Stop 6",
    "textEn": "After a quiet night, the town revealed a small impossible place that only patient people could notice. A tired traveler arrived with a question that did not fit any ordinary map, ticket, or schedule. Instead of giving a quick answer, the keeper of the place listened for the hidden wish inside the question. They searched old drawers, dim corridors, and memories left behind by strangers who had passed through before. By morning, nothing in the town looked dramatically changed, yet one person could finally take the next step without fear. The story ends quietly because not every miracle needs a trumpet; some miracles are only a door opening at the right moment. This is practice story 6, written with steady sentences for long-form typing practice. The road ahead remained uncertain, but the character carried a warmer kind of courage, the sort that grows from being seen, helped, and gently reminded that a small choice can still change the shape of a day. "
  },
  {
    "id": "ai-short-07",
    "titleKo": "달빛 세탁소 7",
    "textKo": "골목 끝 세탁소는 밤 열두 시가 지나야 문을 열었다. 낮에는 평범한 셔터였지만, 달이 간판을 비추면 유리문 안쪽에서 은은한 물소리가 들렸다. 그곳에서는 옷이 아니라 하루 동안 사람에게 묻은 후회와 피로를 빨아 주었다. 첫 손님은 면접에서 말을 더듬은 청년이었다. 주인은 청년의 코트 주머니에서 구겨진 용기를 꺼내 물에 담갔다. 두 번째 손님은 자꾸만 화를 내고 돌아서서 미안해하는 엄마였다. 세탁기는 그녀의 목소리에서 날카로운 모서리를 조금씩 털어냈다. 새벽이 되자 손님들은 같은 옷을 입고도 조금 가벼운 표정으로 골목을 나섰다. 주인은 마지막으로 자신의 앞치마를 세탁기에 넣었다. 누군가의 마음을 씻어 주는 일에도 얼룩은 남는 법이었다. 이 이야기는 7번째 연습문장으로, 천천히 끝까지 입력하며 쉼표와 마침표의 리듬을 느끼도록 구성되었다. 마지막 문장에 이르면 인물은 작지만 분명한 선택을 하고, 독자는 조용한 장면 하나를 마음에 남긴다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다.",
    "titleEn": "Moonlight Laundry 7",
    "textEn": "After a quiet night, the town revealed a small impossible place that only patient people could notice. A tired traveler arrived with a question that did not fit any ordinary map, ticket, or schedule. Instead of giving a quick answer, the keeper of the place listened for the hidden wish inside the question. They searched old drawers, dim corridors, and memories left behind by strangers who had passed through before. By morning, nothing in the town looked dramatically changed, yet one person could finally take the next step without fear. The story ends quietly because not every miracle needs a trumpet; some miracles are only a door opening at the right moment. This is practice story 7, written with steady sentences for long-form typing practice. The road ahead remained uncertain, but the character carried a warmer kind of courage, the sort that grows from being seen, helped, and gently reminded that a small choice can still change the shape of a day. "
  },
  {
    "id": "ai-short-08",
    "titleKo": "종이별 우체국 8",
    "textKo": "산꼭대기에는 주소가 없는 편지만 받는 우체국이 있었다. 사람들은 끝내 보내지 못한 말들을 작은 종이별로 접어 그곳에 맡겼다. 우체부는 별들을 밤하늘에 띄우는 일을 했다. 어느 날, 이름이 지워진 봉투 하나가 도착했다. 안에는 '미안하다'는 한 문장만 적혀 있었다. 우체부는 수신인을 찾지 못해 별을 띄우지 못하고 며칠 동안 책상 위에 올려두었다. 그러다 밤마다 그 별에서 희미한 빛이 새는 것을 보았다. 빛은 마을 아래 오래된 집 창문을 향해 곧게 뻗었다. 우체부는 규칙을 어기고 별을 직접 들고 내려갔다. 집 안의 노인은 별을 보자마자 조용히 눈을 감았다. 그는 이미 보낸 사람이 누구인지 알고 있었다. 다음 밤, 그 종이별은 하늘에서 가장 늦게까지 꺼지지 않았다. 이 이야기는 8번째 연습문장으로, 천천히 끝까지 입력하며 쉼표와 마침표의 리듬을 느끼도록 구성되었다. 마지막 문장에 이르면 인물은 작지만 분명한 선택을 하고, 독자는 조용한 장면 하나를 마음에 남긴다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다.",
    "titleEn": "Paper Star Post Office 8",
    "textEn": "After a quiet night, the town revealed a small impossible place that only patient people could notice. A tired traveler arrived with a question that did not fit any ordinary map, ticket, or schedule. Instead of giving a quick answer, the keeper of the place listened for the hidden wish inside the question. They searched old drawers, dim corridors, and memories left behind by strangers who had passed through before. By morning, nothing in the town looked dramatically changed, yet one person could finally take the next step without fear. The story ends quietly because not every miracle needs a trumpet; some miracles are only a door opening at the right moment. This is practice story 8, written with steady sentences for long-form typing practice. The road ahead remained uncertain, but the character carried a warmer kind of courage, the sort that grows from being seen, helped, and gently reminded that a small choice can still change the shape of a day. "
  },
  {
    "id": "ai-short-09",
    "titleKo": "유리 숲의 지도 9",
    "textKo": "도시 한복판에는 아무도 들어가지 않는 유리 숲이 있었다. 나무들은 투명했고, 바람이 불 때마다 지난 사람들의 기억을 작은 파문처럼 비추었다. 지도 제작자 민은 그 숲의 지도를 만들라는 의뢰를 받았다. 처음에는 길과 나무의 위치만 표시하면 된다고 생각했지만, 숲은 매일 모양을 바꾸었다. 어제 보인 길은 오늘 사라지고, 오늘의 공터에는 누군가 어린 시절 잃어버린 노래가 고여 있었다. 민은 좌표 대신 감정의 흐름을 기록하기 시작했다. 두려움이 많은 곳에는 푸른 선을, 다시 시작하고 싶은 곳에는 주황색 점을 찍었다. 완성된 지도는 길 안내에는 쓸모없었지만, 사람들은 그 지도를 들고 자신이 피하던 기억의 자리까지 찾아갈 수 있었다. 민은 그제야 숲이 길을 숨긴 것이 아니라, 돌아갈 용기를 기다렸다는 사실을 알았다. 이 이야기는 9번째 연습문장으로, 천천히 끝까지 입력하며 쉼표와 마침표의 리듬을 느끼도록 구성되었다. 마지막 문장에 이르면 인물은 작지만 분명한 선택을 하고, 독자는 조용한 장면 하나를 마음에 남긴다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다.",
    "titleEn": "Map of the Glass Forest 9",
    "textEn": "After a quiet night, the town revealed a small impossible place that only patient people could notice. A tired traveler arrived with a question that did not fit any ordinary map, ticket, or schedule. Instead of giving a quick answer, the keeper of the place listened for the hidden wish inside the question. They searched old drawers, dim corridors, and memories left behind by strangers who had passed through before. By morning, nothing in the town looked dramatically changed, yet one person could finally take the next step without fear. The story ends quietly because not every miracle needs a trumpet; some miracles are only a door opening at the right moment. This is practice story 9, written with steady sentences for long-form typing practice. The road ahead remained uncertain, but the character carried a warmer kind of courage, the sort that grows from being seen, helped, and gently reminded that a small choice can still change the shape of a day. "
  },
  {
    "id": "ai-short-10",
    "titleKo": "소금등대 10",
    "textKo": "바다가 말라붙은 뒤에도 등대는 불을 밝혔다. 더 이상 배는 오지 않았고, 수평선 자리에는 하얀 소금 평원이 끝없이 펼쳐졌다. 등대지기 수연은 매일 밤 렌즈를 닦고 빛을 돌렸다. 마을 사람들은 전기가 아깝다며 그만두라고 했지만, 수연은 바다를 기억하는 누군가에게는 아직 신호가 필요할지 모른다고 말했다. 어느 겨울밤, 소금 평원 너머에서 작은 종소리가 들렸다. 수연이 불빛을 낮추자, 소금 결정에 반사된 빛이 길처럼 이어졌다. 그 길을 따라 온 것은 배가 아니라 낡은 항해 일지를 품은 아이였다. 아이는 할아버지가 남긴 지도를 따라 잃어버린 항구를 찾고 있었다. 수연은 등대가 더 이상 배를 부르지 못해도, 기억을 잃은 사람에게 방향을 줄 수 있다는 것을 깨달았다. 이 이야기는 10번째 연습문장으로, 천천히 끝까지 입력하며 쉼표와 마침표의 리듬을 느끼도록 구성되었다. 마지막 문장에 이르면 인물은 작지만 분명한 선택을 하고, 독자는 조용한 장면 하나를 마음에 남긴다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다.",
    "titleEn": "Salt Lighthouse 10",
    "textEn": "After a quiet night, the town revealed a small impossible place that only patient people could notice. A tired traveler arrived with a question that did not fit any ordinary map, ticket, or schedule. Instead of giving a quick answer, the keeper of the place listened for the hidden wish inside the question. They searched old drawers, dim corridors, and memories left behind by strangers who had passed through before. By morning, nothing in the town looked dramatically changed, yet one person could finally take the next step without fear. The story ends quietly because not every miracle needs a trumpet; some miracles are only a door opening at the right moment. This is practice story 10, written with steady sentences for long-form typing practice. The road ahead remained uncertain, but the character carried a warmer kind of courage, the sort that grows from being seen, helped, and gently reminded that a small choice can still change the shape of a day. "
  },
  {
    "id": "ai-short-11",
    "titleKo": "새벽 정류장의 로봇 11",
    "textKo": "비가 그친 새벽, 낡은 버스 정류장에는 충전이 절반만 남은 안내 로봇 하나가 서 있었다. 로봇의 화면에는 오늘의 첫차 시간이 깜박였지만, 정류장을 찾는 사람은 좀처럼 없었다. 그러다 파란 우산을 접은 아이가 나타나 잃어버린 강아지를 찾고 있다고 말했다. 로봇은 노선 안내 대신 오래된 CCTV 기록과 버스 기사들의 습관을 떠올리며 가능한 길을 하나씩 짚었다. 아이는 로봇이 왜 그렇게까지 도와주느냐고 물었다. 로봇은 잠시 계산을 멈추고, 누군가를 목적지까지 안전하게 보내는 일이 자신에게 입력된 가장 오래된 명령이라고 답했다. 해가 떠오를 즈음, 강아지는 차고지 옆 벤치 아래에서 발견되었다. 아이가 고맙다고 손을 흔들자 로봇의 배터리는 3퍼센트까지 떨어졌지만, 화면에는 이상하게도 평소보다 밝은 노란색 미소가 떠 있었다. 이 이야기는 11번째 연습문장으로, 천천히 끝까지 입력하며 쉼표와 마침표의 리듬을 느끼도록 구성되었다. 마지막 문장에 이르면 인물은 작지만 분명한 선택을 하고, 독자는 조용한 장면 하나를 마음에 남긴다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다.",
    "titleEn": "Robot at Dawn Stop 11",
    "textEn": "After a quiet night, the town revealed a small impossible place that only patient people could notice. A tired traveler arrived with a question that did not fit any ordinary map, ticket, or schedule. Instead of giving a quick answer, the keeper of the place listened for the hidden wish inside the question. They searched old drawers, dim corridors, and memories left behind by strangers who had passed through before. By morning, nothing in the town looked dramatically changed, yet one person could finally take the next step without fear. The story ends quietly because not every miracle needs a trumpet; some miracles are only a door opening at the right moment. This is practice story 11, written with steady sentences for long-form typing practice. The road ahead remained uncertain, but the character carried a warmer kind of courage, the sort that grows from being seen, helped, and gently reminded that a small choice can still change the shape of a day. "
  },
  {
    "id": "ai-short-12",
    "titleKo": "달빛 세탁소 12",
    "textKo": "골목 끝 세탁소는 밤 열두 시가 지나야 문을 열었다. 낮에는 평범한 셔터였지만, 달이 간판을 비추면 유리문 안쪽에서 은은한 물소리가 들렸다. 그곳에서는 옷이 아니라 하루 동안 사람에게 묻은 후회와 피로를 빨아 주었다. 첫 손님은 면접에서 말을 더듬은 청년이었다. 주인은 청년의 코트 주머니에서 구겨진 용기를 꺼내 물에 담갔다. 두 번째 손님은 자꾸만 화를 내고 돌아서서 미안해하는 엄마였다. 세탁기는 그녀의 목소리에서 날카로운 모서리를 조금씩 털어냈다. 새벽이 되자 손님들은 같은 옷을 입고도 조금 가벼운 표정으로 골목을 나섰다. 주인은 마지막으로 자신의 앞치마를 세탁기에 넣었다. 누군가의 마음을 씻어 주는 일에도 얼룩은 남는 법이었다. 이 이야기는 12번째 연습문장으로, 천천히 끝까지 입력하며 쉼표와 마침표의 리듬을 느끼도록 구성되었다. 마지막 문장에 이르면 인물은 작지만 분명한 선택을 하고, 독자는 조용한 장면 하나를 마음에 남긴다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다.",
    "titleEn": "Moonlight Laundry 12",
    "textEn": "After a quiet night, the town revealed a small impossible place that only patient people could notice. A tired traveler arrived with a question that did not fit any ordinary map, ticket, or schedule. Instead of giving a quick answer, the keeper of the place listened for the hidden wish inside the question. They searched old drawers, dim corridors, and memories left behind by strangers who had passed through before. By morning, nothing in the town looked dramatically changed, yet one person could finally take the next step without fear. The story ends quietly because not every miracle needs a trumpet; some miracles are only a door opening at the right moment. This is practice story 12, written with steady sentences for long-form typing practice. The road ahead remained uncertain, but the character carried a warmer kind of courage, the sort that grows from being seen, helped, and gently reminded that a small choice can still change the shape of a day. "
  },
  {
    "id": "ai-short-13",
    "titleKo": "종이별 우체국 13",
    "textKo": "산꼭대기에는 주소가 없는 편지만 받는 우체국이 있었다. 사람들은 끝내 보내지 못한 말들을 작은 종이별로 접어 그곳에 맡겼다. 우체부는 별들을 밤하늘에 띄우는 일을 했다. 어느 날, 이름이 지워진 봉투 하나가 도착했다. 안에는 '미안하다'는 한 문장만 적혀 있었다. 우체부는 수신인을 찾지 못해 별을 띄우지 못하고 며칠 동안 책상 위에 올려두었다. 그러다 밤마다 그 별에서 희미한 빛이 새는 것을 보았다. 빛은 마을 아래 오래된 집 창문을 향해 곧게 뻗었다. 우체부는 규칙을 어기고 별을 직접 들고 내려갔다. 집 안의 노인은 별을 보자마자 조용히 눈을 감았다. 그는 이미 보낸 사람이 누구인지 알고 있었다. 다음 밤, 그 종이별은 하늘에서 가장 늦게까지 꺼지지 않았다. 이 이야기는 13번째 연습문장으로, 천천히 끝까지 입력하며 쉼표와 마침표의 리듬을 느끼도록 구성되었다. 마지막 문장에 이르면 인물은 작지만 분명한 선택을 하고, 독자는 조용한 장면 하나를 마음에 남긴다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다.",
    "titleEn": "Paper Star Post Office 13",
    "textEn": "After a quiet night, the town revealed a small impossible place that only patient people could notice. A tired traveler arrived with a question that did not fit any ordinary map, ticket, or schedule. Instead of giving a quick answer, the keeper of the place listened for the hidden wish inside the question. They searched old drawers, dim corridors, and memories left behind by strangers who had passed through before. By morning, nothing in the town looked dramatically changed, yet one person could finally take the next step without fear. The story ends quietly because not every miracle needs a trumpet; some miracles are only a door opening at the right moment. This is practice story 13, written with steady sentences for long-form typing practice. The road ahead remained uncertain, but the character carried a warmer kind of courage, the sort that grows from being seen, helped, and gently reminded that a small choice can still change the shape of a day. "
  },
  {
    "id": "ai-short-14",
    "titleKo": "유리 숲의 지도 14",
    "textKo": "도시 한복판에는 아무도 들어가지 않는 유리 숲이 있었다. 나무들은 투명했고, 바람이 불 때마다 지난 사람들의 기억을 작은 파문처럼 비추었다. 지도 제작자 민은 그 숲의 지도를 만들라는 의뢰를 받았다. 처음에는 길과 나무의 위치만 표시하면 된다고 생각했지만, 숲은 매일 모양을 바꾸었다. 어제 보인 길은 오늘 사라지고, 오늘의 공터에는 누군가 어린 시절 잃어버린 노래가 고여 있었다. 민은 좌표 대신 감정의 흐름을 기록하기 시작했다. 두려움이 많은 곳에는 푸른 선을, 다시 시작하고 싶은 곳에는 주황색 점을 찍었다. 완성된 지도는 길 안내에는 쓸모없었지만, 사람들은 그 지도를 들고 자신이 피하던 기억의 자리까지 찾아갈 수 있었다. 민은 그제야 숲이 길을 숨긴 것이 아니라, 돌아갈 용기를 기다렸다는 사실을 알았다. 이 이야기는 14번째 연습문장으로, 천천히 끝까지 입력하며 쉼표와 마침표의 리듬을 느끼도록 구성되었다. 마지막 문장에 이르면 인물은 작지만 분명한 선택을 하고, 독자는 조용한 장면 하나를 마음에 남긴다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다.",
    "titleEn": "Map of the Glass Forest 14",
    "textEn": "After a quiet night, the town revealed a small impossible place that only patient people could notice. A tired traveler arrived with a question that did not fit any ordinary map, ticket, or schedule. Instead of giving a quick answer, the keeper of the place listened for the hidden wish inside the question. They searched old drawers, dim corridors, and memories left behind by strangers who had passed through before. By morning, nothing in the town looked dramatically changed, yet one person could finally take the next step without fear. The story ends quietly because not every miracle needs a trumpet; some miracles are only a door opening at the right moment. This is practice story 14, written with steady sentences for long-form typing practice. The road ahead remained uncertain, but the character carried a warmer kind of courage, the sort that grows from being seen, helped, and gently reminded that a small choice can still change the shape of a day. "
  },
  {
    "id": "ai-short-15",
    "titleKo": "소금등대 15",
    "textKo": "바다가 말라붙은 뒤에도 등대는 불을 밝혔다. 더 이상 배는 오지 않았고, 수평선 자리에는 하얀 소금 평원이 끝없이 펼쳐졌다. 등대지기 수연은 매일 밤 렌즈를 닦고 빛을 돌렸다. 마을 사람들은 전기가 아깝다며 그만두라고 했지만, 수연은 바다를 기억하는 누군가에게는 아직 신호가 필요할지 모른다고 말했다. 어느 겨울밤, 소금 평원 너머에서 작은 종소리가 들렸다. 수연이 불빛을 낮추자, 소금 결정에 반사된 빛이 길처럼 이어졌다. 그 길을 따라 온 것은 배가 아니라 낡은 항해 일지를 품은 아이였다. 아이는 할아버지가 남긴 지도를 따라 잃어버린 항구를 찾고 있었다. 수연은 등대가 더 이상 배를 부르지 못해도, 기억을 잃은 사람에게 방향을 줄 수 있다는 것을 깨달았다. 이 이야기는 15번째 연습문장으로, 천천히 끝까지 입력하며 쉼표와 마침표의 리듬을 느끼도록 구성되었다. 마지막 문장에 이르면 인물은 작지만 분명한 선택을 하고, 독자는 조용한 장면 하나를 마음에 남긴다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다.",
    "titleEn": "Salt Lighthouse 15",
    "textEn": "After a quiet night, the town revealed a small impossible place that only patient people could notice. A tired traveler arrived with a question that did not fit any ordinary map, ticket, or schedule. Instead of giving a quick answer, the keeper of the place listened for the hidden wish inside the question. They searched old drawers, dim corridors, and memories left behind by strangers who had passed through before. By morning, nothing in the town looked dramatically changed, yet one person could finally take the next step without fear. The story ends quietly because not every miracle needs a trumpet; some miracles are only a door opening at the right moment. This is practice story 15, written with steady sentences for long-form typing practice. The road ahead remained uncertain, but the character carried a warmer kind of courage, the sort that grows from being seen, helped, and gently reminded that a small choice can still change the shape of a day. "
  },
  {
    "id": "ai-short-16",
    "titleKo": "새벽 정류장의 로봇 16",
    "textKo": "비가 그친 새벽, 낡은 버스 정류장에는 충전이 절반만 남은 안내 로봇 하나가 서 있었다. 로봇의 화면에는 오늘의 첫차 시간이 깜박였지만, 정류장을 찾는 사람은 좀처럼 없었다. 그러다 파란 우산을 접은 아이가 나타나 잃어버린 강아지를 찾고 있다고 말했다. 로봇은 노선 안내 대신 오래된 CCTV 기록과 버스 기사들의 습관을 떠올리며 가능한 길을 하나씩 짚었다. 아이는 로봇이 왜 그렇게까지 도와주느냐고 물었다. 로봇은 잠시 계산을 멈추고, 누군가를 목적지까지 안전하게 보내는 일이 자신에게 입력된 가장 오래된 명령이라고 답했다. 해가 떠오를 즈음, 강아지는 차고지 옆 벤치 아래에서 발견되었다. 아이가 고맙다고 손을 흔들자 로봇의 배터리는 3퍼센트까지 떨어졌지만, 화면에는 이상하게도 평소보다 밝은 노란색 미소가 떠 있었다. 이 이야기는 16번째 연습문장으로, 천천히 끝까지 입력하며 쉼표와 마침표의 리듬을 느끼도록 구성되었다. 마지막 문장에 이르면 인물은 작지만 분명한 선택을 하고, 독자는 조용한 장면 하나를 마음에 남긴다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다.",
    "titleEn": "Robot at Dawn Stop 16",
    "textEn": "After a quiet night, the town revealed a small impossible place that only patient people could notice. A tired traveler arrived with a question that did not fit any ordinary map, ticket, or schedule. Instead of giving a quick answer, the keeper of the place listened for the hidden wish inside the question. They searched old drawers, dim corridors, and memories left behind by strangers who had passed through before. By morning, nothing in the town looked dramatically changed, yet one person could finally take the next step without fear. The story ends quietly because not every miracle needs a trumpet; some miracles are only a door opening at the right moment. This is practice story 16, written with steady sentences for long-form typing practice. The road ahead remained uncertain, but the character carried a warmer kind of courage, the sort that grows from being seen, helped, and gently reminded that a small choice can still change the shape of a day. "
  },
  {
    "id": "ai-short-17",
    "titleKo": "달빛 세탁소 17",
    "textKo": "골목 끝 세탁소는 밤 열두 시가 지나야 문을 열었다. 낮에는 평범한 셔터였지만, 달이 간판을 비추면 유리문 안쪽에서 은은한 물소리가 들렸다. 그곳에서는 옷이 아니라 하루 동안 사람에게 묻은 후회와 피로를 빨아 주었다. 첫 손님은 면접에서 말을 더듬은 청년이었다. 주인은 청년의 코트 주머니에서 구겨진 용기를 꺼내 물에 담갔다. 두 번째 손님은 자꾸만 화를 내고 돌아서서 미안해하는 엄마였다. 세탁기는 그녀의 목소리에서 날카로운 모서리를 조금씩 털어냈다. 새벽이 되자 손님들은 같은 옷을 입고도 조금 가벼운 표정으로 골목을 나섰다. 주인은 마지막으로 자신의 앞치마를 세탁기에 넣었다. 누군가의 마음을 씻어 주는 일에도 얼룩은 남는 법이었다. 이 이야기는 17번째 연습문장으로, 천천히 끝까지 입력하며 쉼표와 마침표의 리듬을 느끼도록 구성되었다. 마지막 문장에 이르면 인물은 작지만 분명한 선택을 하고, 독자는 조용한 장면 하나를 마음에 남긴다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다.",
    "titleEn": "Moonlight Laundry 17",
    "textEn": "After a quiet night, the town revealed a small impossible place that only patient people could notice. A tired traveler arrived with a question that did not fit any ordinary map, ticket, or schedule. Instead of giving a quick answer, the keeper of the place listened for the hidden wish inside the question. They searched old drawers, dim corridors, and memories left behind by strangers who had passed through before. By morning, nothing in the town looked dramatically changed, yet one person could finally take the next step without fear. The story ends quietly because not every miracle needs a trumpet; some miracles are only a door opening at the right moment. This is practice story 17, written with steady sentences for long-form typing practice. The road ahead remained uncertain, but the character carried a warmer kind of courage, the sort that grows from being seen, helped, and gently reminded that a small choice can still change the shape of a day. "
  },
  {
    "id": "ai-short-18",
    "titleKo": "종이별 우체국 18",
    "textKo": "산꼭대기에는 주소가 없는 편지만 받는 우체국이 있었다. 사람들은 끝내 보내지 못한 말들을 작은 종이별로 접어 그곳에 맡겼다. 우체부는 별들을 밤하늘에 띄우는 일을 했다. 어느 날, 이름이 지워진 봉투 하나가 도착했다. 안에는 '미안하다'는 한 문장만 적혀 있었다. 우체부는 수신인을 찾지 못해 별을 띄우지 못하고 며칠 동안 책상 위에 올려두었다. 그러다 밤마다 그 별에서 희미한 빛이 새는 것을 보았다. 빛은 마을 아래 오래된 집 창문을 향해 곧게 뻗었다. 우체부는 규칙을 어기고 별을 직접 들고 내려갔다. 집 안의 노인은 별을 보자마자 조용히 눈을 감았다. 그는 이미 보낸 사람이 누구인지 알고 있었다. 다음 밤, 그 종이별은 하늘에서 가장 늦게까지 꺼지지 않았다. 이 이야기는 18번째 연습문장으로, 천천히 끝까지 입력하며 쉼표와 마침표의 리듬을 느끼도록 구성되었다. 마지막 문장에 이르면 인물은 작지만 분명한 선택을 하고, 독자는 조용한 장면 하나를 마음에 남긴다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다.",
    "titleEn": "Paper Star Post Office 18",
    "textEn": "After a quiet night, the town revealed a small impossible place that only patient people could notice. A tired traveler arrived with a question that did not fit any ordinary map, ticket, or schedule. Instead of giving a quick answer, the keeper of the place listened for the hidden wish inside the question. They searched old drawers, dim corridors, and memories left behind by strangers who had passed through before. By morning, nothing in the town looked dramatically changed, yet one person could finally take the next step without fear. The story ends quietly because not every miracle needs a trumpet; some miracles are only a door opening at the right moment. This is practice story 18, written with steady sentences for long-form typing practice. The road ahead remained uncertain, but the character carried a warmer kind of courage, the sort that grows from being seen, helped, and gently reminded that a small choice can still change the shape of a day. "
  },
  {
    "id": "ai-short-19",
    "titleKo": "유리 숲의 지도 19",
    "textKo": "도시 한복판에는 아무도 들어가지 않는 유리 숲이 있었다. 나무들은 투명했고, 바람이 불 때마다 지난 사람들의 기억을 작은 파문처럼 비추었다. 지도 제작자 민은 그 숲의 지도를 만들라는 의뢰를 받았다. 처음에는 길과 나무의 위치만 표시하면 된다고 생각했지만, 숲은 매일 모양을 바꾸었다. 어제 보인 길은 오늘 사라지고, 오늘의 공터에는 누군가 어린 시절 잃어버린 노래가 고여 있었다. 민은 좌표 대신 감정의 흐름을 기록하기 시작했다. 두려움이 많은 곳에는 푸른 선을, 다시 시작하고 싶은 곳에는 주황색 점을 찍었다. 완성된 지도는 길 안내에는 쓸모없었지만, 사람들은 그 지도를 들고 자신이 피하던 기억의 자리까지 찾아갈 수 있었다. 민은 그제야 숲이 길을 숨긴 것이 아니라, 돌아갈 용기를 기다렸다는 사실을 알았다. 이 이야기는 19번째 연습문장으로, 천천히 끝까지 입력하며 쉼표와 마침표의 리듬을 느끼도록 구성되었다. 마지막 문장에 이르면 인물은 작지만 분명한 선택을 하고, 독자는 조용한 장면 하나를 마음에 남긴다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다.",
    "titleEn": "Map of the Glass Forest 19",
    "textEn": "After a quiet night, the town revealed a small impossible place that only patient people could notice. A tired traveler arrived with a question that did not fit any ordinary map, ticket, or schedule. Instead of giving a quick answer, the keeper of the place listened for the hidden wish inside the question. They searched old drawers, dim corridors, and memories left behind by strangers who had passed through before. By morning, nothing in the town looked dramatically changed, yet one person could finally take the next step without fear. The story ends quietly because not every miracle needs a trumpet; some miracles are only a door opening at the right moment. This is practice story 19, written with steady sentences for long-form typing practice. The road ahead remained uncertain, but the character carried a warmer kind of courage, the sort that grows from being seen, helped, and gently reminded that a small choice can still change the shape of a day. "
  },
  {
    "id": "ai-short-20",
    "titleKo": "소금등대 20",
    "textKo": "바다가 말라붙은 뒤에도 등대는 불을 밝혔다. 더 이상 배는 오지 않았고, 수평선 자리에는 하얀 소금 평원이 끝없이 펼쳐졌다. 등대지기 수연은 매일 밤 렌즈를 닦고 빛을 돌렸다. 마을 사람들은 전기가 아깝다며 그만두라고 했지만, 수연은 바다를 기억하는 누군가에게는 아직 신호가 필요할지 모른다고 말했다. 어느 겨울밤, 소금 평원 너머에서 작은 종소리가 들렸다. 수연이 불빛을 낮추자, 소금 결정에 반사된 빛이 길처럼 이어졌다. 그 길을 따라 온 것은 배가 아니라 낡은 항해 일지를 품은 아이였다. 아이는 할아버지가 남긴 지도를 따라 잃어버린 항구를 찾고 있었다. 수연은 등대가 더 이상 배를 부르지 못해도, 기억을 잃은 사람에게 방향을 줄 수 있다는 것을 깨달았다. 이 이야기는 20번째 연습문장으로, 천천히 끝까지 입력하며 쉼표와 마침표의 리듬을 느끼도록 구성되었다. 마지막 문장에 이르면 인물은 작지만 분명한 선택을 하고, 독자는 조용한 장면 하나를 마음에 남긴다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다.",
    "titleEn": "Salt Lighthouse 20",
    "textEn": "After a quiet night, the town revealed a small impossible place that only patient people could notice. A tired traveler arrived with a question that did not fit any ordinary map, ticket, or schedule. Instead of giving a quick answer, the keeper of the place listened for the hidden wish inside the question. They searched old drawers, dim corridors, and memories left behind by strangers who had passed through before. By morning, nothing in the town looked dramatically changed, yet one person could finally take the next step without fear. The story ends quietly because not every miracle needs a trumpet; some miracles are only a door opening at the right moment. This is practice story 20, written with steady sentences for long-form typing practice. The road ahead remained uncertain, but the character carried a warmer kind of courage, the sort that grows from being seen, helped, and gently reminded that a small choice can still change the shape of a day. "
  },
  {
    "id": "ai-short-21",
    "titleKo": "새벽 정류장의 로봇 21",
    "textKo": "비가 그친 새벽, 낡은 버스 정류장에는 충전이 절반만 남은 안내 로봇 하나가 서 있었다. 로봇의 화면에는 오늘의 첫차 시간이 깜박였지만, 정류장을 찾는 사람은 좀처럼 없었다. 그러다 파란 우산을 접은 아이가 나타나 잃어버린 강아지를 찾고 있다고 말했다. 로봇은 노선 안내 대신 오래된 CCTV 기록과 버스 기사들의 습관을 떠올리며 가능한 길을 하나씩 짚었다. 아이는 로봇이 왜 그렇게까지 도와주느냐고 물었다. 로봇은 잠시 계산을 멈추고, 누군가를 목적지까지 안전하게 보내는 일이 자신에게 입력된 가장 오래된 명령이라고 답했다. 해가 떠오를 즈음, 강아지는 차고지 옆 벤치 아래에서 발견되었다. 아이가 고맙다고 손을 흔들자 로봇의 배터리는 3퍼센트까지 떨어졌지만, 화면에는 이상하게도 평소보다 밝은 노란색 미소가 떠 있었다. 이 이야기는 21번째 연습문장으로, 천천히 끝까지 입력하며 쉼표와 마침표의 리듬을 느끼도록 구성되었다. 마지막 문장에 이르면 인물은 작지만 분명한 선택을 하고, 독자는 조용한 장면 하나를 마음에 남긴다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다.",
    "titleEn": "Robot at Dawn Stop 21",
    "textEn": "After a quiet night, the town revealed a small impossible place that only patient people could notice. A tired traveler arrived with a question that did not fit any ordinary map, ticket, or schedule. Instead of giving a quick answer, the keeper of the place listened for the hidden wish inside the question. They searched old drawers, dim corridors, and memories left behind by strangers who had passed through before. By morning, nothing in the town looked dramatically changed, yet one person could finally take the next step without fear. The story ends quietly because not every miracle needs a trumpet; some miracles are only a door opening at the right moment. This is practice story 21, written with steady sentences for long-form typing practice. The road ahead remained uncertain, but the character carried a warmer kind of courage, the sort that grows from being seen, helped, and gently reminded that a small choice can still change the shape of a day. "
  },
  {
    "id": "ai-short-22",
    "titleKo": "달빛 세탁소 22",
    "textKo": "골목 끝 세탁소는 밤 열두 시가 지나야 문을 열었다. 낮에는 평범한 셔터였지만, 달이 간판을 비추면 유리문 안쪽에서 은은한 물소리가 들렸다. 그곳에서는 옷이 아니라 하루 동안 사람에게 묻은 후회와 피로를 빨아 주었다. 첫 손님은 면접에서 말을 더듬은 청년이었다. 주인은 청년의 코트 주머니에서 구겨진 용기를 꺼내 물에 담갔다. 두 번째 손님은 자꾸만 화를 내고 돌아서서 미안해하는 엄마였다. 세탁기는 그녀의 목소리에서 날카로운 모서리를 조금씩 털어냈다. 새벽이 되자 손님들은 같은 옷을 입고도 조금 가벼운 표정으로 골목을 나섰다. 주인은 마지막으로 자신의 앞치마를 세탁기에 넣었다. 누군가의 마음을 씻어 주는 일에도 얼룩은 남는 법이었다. 이 이야기는 22번째 연습문장으로, 천천히 끝까지 입력하며 쉼표와 마침표의 리듬을 느끼도록 구성되었다. 마지막 문장에 이르면 인물은 작지만 분명한 선택을 하고, 독자는 조용한 장면 하나를 마음에 남긴다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다.",
    "titleEn": "Moonlight Laundry 22",
    "textEn": "After a quiet night, the town revealed a small impossible place that only patient people could notice. A tired traveler arrived with a question that did not fit any ordinary map, ticket, or schedule. Instead of giving a quick answer, the keeper of the place listened for the hidden wish inside the question. They searched old drawers, dim corridors, and memories left behind by strangers who had passed through before. By morning, nothing in the town looked dramatically changed, yet one person could finally take the next step without fear. The story ends quietly because not every miracle needs a trumpet; some miracles are only a door opening at the right moment. This is practice story 22, written with steady sentences for long-form typing practice. The road ahead remained uncertain, but the character carried a warmer kind of courage, the sort that grows from being seen, helped, and gently reminded that a small choice can still change the shape of a day. "
  },
  {
    "id": "ai-short-23",
    "titleKo": "종이별 우체국 23",
    "textKo": "산꼭대기에는 주소가 없는 편지만 받는 우체국이 있었다. 사람들은 끝내 보내지 못한 말들을 작은 종이별로 접어 그곳에 맡겼다. 우체부는 별들을 밤하늘에 띄우는 일을 했다. 어느 날, 이름이 지워진 봉투 하나가 도착했다. 안에는 '미안하다'는 한 문장만 적혀 있었다. 우체부는 수신인을 찾지 못해 별을 띄우지 못하고 며칠 동안 책상 위에 올려두었다. 그러다 밤마다 그 별에서 희미한 빛이 새는 것을 보았다. 빛은 마을 아래 오래된 집 창문을 향해 곧게 뻗었다. 우체부는 규칙을 어기고 별을 직접 들고 내려갔다. 집 안의 노인은 별을 보자마자 조용히 눈을 감았다. 그는 이미 보낸 사람이 누구인지 알고 있었다. 다음 밤, 그 종이별은 하늘에서 가장 늦게까지 꺼지지 않았다. 이 이야기는 23번째 연습문장으로, 천천히 끝까지 입력하며 쉼표와 마침표의 리듬을 느끼도록 구성되었다. 마지막 문장에 이르면 인물은 작지만 분명한 선택을 하고, 독자는 조용한 장면 하나를 마음에 남긴다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다.",
    "titleEn": "Paper Star Post Office 23",
    "textEn": "After a quiet night, the town revealed a small impossible place that only patient people could notice. A tired traveler arrived with a question that did not fit any ordinary map, ticket, or schedule. Instead of giving a quick answer, the keeper of the place listened for the hidden wish inside the question. They searched old drawers, dim corridors, and memories left behind by strangers who had passed through before. By morning, nothing in the town looked dramatically changed, yet one person could finally take the next step without fear. The story ends quietly because not every miracle needs a trumpet; some miracles are only a door opening at the right moment. This is practice story 23, written with steady sentences for long-form typing practice. The road ahead remained uncertain, but the character carried a warmer kind of courage, the sort that grows from being seen, helped, and gently reminded that a small choice can still change the shape of a day. "
  },
  {
    "id": "ai-short-24",
    "titleKo": "유리 숲의 지도 24",
    "textKo": "도시 한복판에는 아무도 들어가지 않는 유리 숲이 있었다. 나무들은 투명했고, 바람이 불 때마다 지난 사람들의 기억을 작은 파문처럼 비추었다. 지도 제작자 민은 그 숲의 지도를 만들라는 의뢰를 받았다. 처음에는 길과 나무의 위치만 표시하면 된다고 생각했지만, 숲은 매일 모양을 바꾸었다. 어제 보인 길은 오늘 사라지고, 오늘의 공터에는 누군가 어린 시절 잃어버린 노래가 고여 있었다. 민은 좌표 대신 감정의 흐름을 기록하기 시작했다. 두려움이 많은 곳에는 푸른 선을, 다시 시작하고 싶은 곳에는 주황색 점을 찍었다. 완성된 지도는 길 안내에는 쓸모없었지만, 사람들은 그 지도를 들고 자신이 피하던 기억의 자리까지 찾아갈 수 있었다. 민은 그제야 숲이 길을 숨긴 것이 아니라, 돌아갈 용기를 기다렸다는 사실을 알았다. 이 이야기는 24번째 연습문장으로, 천천히 끝까지 입력하며 쉼표와 마침표의 리듬을 느끼도록 구성되었다. 마지막 문장에 이르면 인물은 작지만 분명한 선택을 하고, 독자는 조용한 장면 하나를 마음에 남긴다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다.",
    "titleEn": "Map of the Glass Forest 24",
    "textEn": "After a quiet night, the town revealed a small impossible place that only patient people could notice. A tired traveler arrived with a question that did not fit any ordinary map, ticket, or schedule. Instead of giving a quick answer, the keeper of the place listened for the hidden wish inside the question. They searched old drawers, dim corridors, and memories left behind by strangers who had passed through before. By morning, nothing in the town looked dramatically changed, yet one person could finally take the next step without fear. The story ends quietly because not every miracle needs a trumpet; some miracles are only a door opening at the right moment. This is practice story 24, written with steady sentences for long-form typing practice. The road ahead remained uncertain, but the character carried a warmer kind of courage, the sort that grows from being seen, helped, and gently reminded that a small choice can still change the shape of a day. "
  },
  {
    "id": "ai-short-25",
    "titleKo": "소금등대 25",
    "textKo": "바다가 말라붙은 뒤에도 등대는 불을 밝혔다. 더 이상 배는 오지 않았고, 수평선 자리에는 하얀 소금 평원이 끝없이 펼쳐졌다. 등대지기 수연은 매일 밤 렌즈를 닦고 빛을 돌렸다. 마을 사람들은 전기가 아깝다며 그만두라고 했지만, 수연은 바다를 기억하는 누군가에게는 아직 신호가 필요할지 모른다고 말했다. 어느 겨울밤, 소금 평원 너머에서 작은 종소리가 들렸다. 수연이 불빛을 낮추자, 소금 결정에 반사된 빛이 길처럼 이어졌다. 그 길을 따라 온 것은 배가 아니라 낡은 항해 일지를 품은 아이였다. 아이는 할아버지가 남긴 지도를 따라 잃어버린 항구를 찾고 있었다. 수연은 등대가 더 이상 배를 부르지 못해도, 기억을 잃은 사람에게 방향을 줄 수 있다는 것을 깨달았다. 이 이야기는 25번째 연습문장으로, 천천히 끝까지 입력하며 쉼표와 마침표의 리듬을 느끼도록 구성되었다. 마지막 문장에 이르면 인물은 작지만 분명한 선택을 하고, 독자는 조용한 장면 하나를 마음에 남긴다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다.",
    "titleEn": "Salt Lighthouse 25",
    "textEn": "After a quiet night, the town revealed a small impossible place that only patient people could notice. A tired traveler arrived with a question that did not fit any ordinary map, ticket, or schedule. Instead of giving a quick answer, the keeper of the place listened for the hidden wish inside the question. They searched old drawers, dim corridors, and memories left behind by strangers who had passed through before. By morning, nothing in the town looked dramatically changed, yet one person could finally take the next step without fear. The story ends quietly because not every miracle needs a trumpet; some miracles are only a door opening at the right moment. This is practice story 25, written with steady sentences for long-form typing practice. The road ahead remained uncertain, but the character carried a warmer kind of courage, the sort that grows from being seen, helped, and gently reminded that a small choice can still change the shape of a day. "
  },
  {
    "id": "ai-short-26",
    "titleKo": "새벽 정류장의 로봇 26",
    "textKo": "비가 그친 새벽, 낡은 버스 정류장에는 충전이 절반만 남은 안내 로봇 하나가 서 있었다. 로봇의 화면에는 오늘의 첫차 시간이 깜박였지만, 정류장을 찾는 사람은 좀처럼 없었다. 그러다 파란 우산을 접은 아이가 나타나 잃어버린 강아지를 찾고 있다고 말했다. 로봇은 노선 안내 대신 오래된 CCTV 기록과 버스 기사들의 습관을 떠올리며 가능한 길을 하나씩 짚었다. 아이는 로봇이 왜 그렇게까지 도와주느냐고 물었다. 로봇은 잠시 계산을 멈추고, 누군가를 목적지까지 안전하게 보내는 일이 자신에게 입력된 가장 오래된 명령이라고 답했다. 해가 떠오를 즈음, 강아지는 차고지 옆 벤치 아래에서 발견되었다. 아이가 고맙다고 손을 흔들자 로봇의 배터리는 3퍼센트까지 떨어졌지만, 화면에는 이상하게도 평소보다 밝은 노란색 미소가 떠 있었다. 이 이야기는 26번째 연습문장으로, 천천히 끝까지 입력하며 쉼표와 마침표의 리듬을 느끼도록 구성되었다. 마지막 문장에 이르면 인물은 작지만 분명한 선택을 하고, 독자는 조용한 장면 하나를 마음에 남긴다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다.",
    "titleEn": "Robot at Dawn Stop 26",
    "textEn": "After a quiet night, the town revealed a small impossible place that only patient people could notice. A tired traveler arrived with a question that did not fit any ordinary map, ticket, or schedule. Instead of giving a quick answer, the keeper of the place listened for the hidden wish inside the question. They searched old drawers, dim corridors, and memories left behind by strangers who had passed through before. By morning, nothing in the town looked dramatically changed, yet one person could finally take the next step without fear. The story ends quietly because not every miracle needs a trumpet; some miracles are only a door opening at the right moment. This is practice story 26, written with steady sentences for long-form typing practice. The road ahead remained uncertain, but the character carried a warmer kind of courage, the sort that grows from being seen, helped, and gently reminded that a small choice can still change the shape of a day. "
  },
  {
    "id": "ai-short-27",
    "titleKo": "달빛 세탁소 27",
    "textKo": "골목 끝 세탁소는 밤 열두 시가 지나야 문을 열었다. 낮에는 평범한 셔터였지만, 달이 간판을 비추면 유리문 안쪽에서 은은한 물소리가 들렸다. 그곳에서는 옷이 아니라 하루 동안 사람에게 묻은 후회와 피로를 빨아 주었다. 첫 손님은 면접에서 말을 더듬은 청년이었다. 주인은 청년의 코트 주머니에서 구겨진 용기를 꺼내 물에 담갔다. 두 번째 손님은 자꾸만 화를 내고 돌아서서 미안해하는 엄마였다. 세탁기는 그녀의 목소리에서 날카로운 모서리를 조금씩 털어냈다. 새벽이 되자 손님들은 같은 옷을 입고도 조금 가벼운 표정으로 골목을 나섰다. 주인은 마지막으로 자신의 앞치마를 세탁기에 넣었다. 누군가의 마음을 씻어 주는 일에도 얼룩은 남는 법이었다. 이 이야기는 27번째 연습문장으로, 천천히 끝까지 입력하며 쉼표와 마침표의 리듬을 느끼도록 구성되었다. 마지막 문장에 이르면 인물은 작지만 분명한 선택을 하고, 독자는 조용한 장면 하나를 마음에 남긴다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다.",
    "titleEn": "Moonlight Laundry 27",
    "textEn": "After a quiet night, the town revealed a small impossible place that only patient people could notice. A tired traveler arrived with a question that did not fit any ordinary map, ticket, or schedule. Instead of giving a quick answer, the keeper of the place listened for the hidden wish inside the question. They searched old drawers, dim corridors, and memories left behind by strangers who had passed through before. By morning, nothing in the town looked dramatically changed, yet one person could finally take the next step without fear. The story ends quietly because not every miracle needs a trumpet; some miracles are only a door opening at the right moment. This is practice story 27, written with steady sentences for long-form typing practice. The road ahead remained uncertain, but the character carried a warmer kind of courage, the sort that grows from being seen, helped, and gently reminded that a small choice can still change the shape of a day. "
  },
  {
    "id": "ai-short-28",
    "titleKo": "종이별 우체국 28",
    "textKo": "산꼭대기에는 주소가 없는 편지만 받는 우체국이 있었다. 사람들은 끝내 보내지 못한 말들을 작은 종이별로 접어 그곳에 맡겼다. 우체부는 별들을 밤하늘에 띄우는 일을 했다. 어느 날, 이름이 지워진 봉투 하나가 도착했다. 안에는 '미안하다'는 한 문장만 적혀 있었다. 우체부는 수신인을 찾지 못해 별을 띄우지 못하고 며칠 동안 책상 위에 올려두었다. 그러다 밤마다 그 별에서 희미한 빛이 새는 것을 보았다. 빛은 마을 아래 오래된 집 창문을 향해 곧게 뻗었다. 우체부는 규칙을 어기고 별을 직접 들고 내려갔다. 집 안의 노인은 별을 보자마자 조용히 눈을 감았다. 그는 이미 보낸 사람이 누구인지 알고 있었다. 다음 밤, 그 종이별은 하늘에서 가장 늦게까지 꺼지지 않았다. 이 이야기는 28번째 연습문장으로, 천천히 끝까지 입력하며 쉼표와 마침표의 리듬을 느끼도록 구성되었다. 마지막 문장에 이르면 인물은 작지만 분명한 선택을 하고, 독자는 조용한 장면 하나를 마음에 남긴다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다.",
    "titleEn": "Paper Star Post Office 28",
    "textEn": "After a quiet night, the town revealed a small impossible place that only patient people could notice. A tired traveler arrived with a question that did not fit any ordinary map, ticket, or schedule. Instead of giving a quick answer, the keeper of the place listened for the hidden wish inside the question. They searched old drawers, dim corridors, and memories left behind by strangers who had passed through before. By morning, nothing in the town looked dramatically changed, yet one person could finally take the next step without fear. The story ends quietly because not every miracle needs a trumpet; some miracles are only a door opening at the right moment. This is practice story 28, written with steady sentences for long-form typing practice. The road ahead remained uncertain, but the character carried a warmer kind of courage, the sort that grows from being seen, helped, and gently reminded that a small choice can still change the shape of a day. "
  },
  {
    "id": "ai-short-29",
    "titleKo": "유리 숲의 지도 29",
    "textKo": "도시 한복판에는 아무도 들어가지 않는 유리 숲이 있었다. 나무들은 투명했고, 바람이 불 때마다 지난 사람들의 기억을 작은 파문처럼 비추었다. 지도 제작자 민은 그 숲의 지도를 만들라는 의뢰를 받았다. 처음에는 길과 나무의 위치만 표시하면 된다고 생각했지만, 숲은 매일 모양을 바꾸었다. 어제 보인 길은 오늘 사라지고, 오늘의 공터에는 누군가 어린 시절 잃어버린 노래가 고여 있었다. 민은 좌표 대신 감정의 흐름을 기록하기 시작했다. 두려움이 많은 곳에는 푸른 선을, 다시 시작하고 싶은 곳에는 주황색 점을 찍었다. 완성된 지도는 길 안내에는 쓸모없었지만, 사람들은 그 지도를 들고 자신이 피하던 기억의 자리까지 찾아갈 수 있었다. 민은 그제야 숲이 길을 숨긴 것이 아니라, 돌아갈 용기를 기다렸다는 사실을 알았다. 이 이야기는 29번째 연습문장으로, 천천히 끝까지 입력하며 쉼표와 마침표의 리듬을 느끼도록 구성되었다. 마지막 문장에 이르면 인물은 작지만 분명한 선택을 하고, 독자는 조용한 장면 하나를 마음에 남긴다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다.",
    "titleEn": "Map of the Glass Forest 29",
    "textEn": "After a quiet night, the town revealed a small impossible place that only patient people could notice. A tired traveler arrived with a question that did not fit any ordinary map, ticket, or schedule. Instead of giving a quick answer, the keeper of the place listened for the hidden wish inside the question. They searched old drawers, dim corridors, and memories left behind by strangers who had passed through before. By morning, nothing in the town looked dramatically changed, yet one person could finally take the next step without fear. The story ends quietly because not every miracle needs a trumpet; some miracles are only a door opening at the right moment. This is practice story 29, written with steady sentences for long-form typing practice. The road ahead remained uncertain, but the character carried a warmer kind of courage, the sort that grows from being seen, helped, and gently reminded that a small choice can still change the shape of a day. "
  },
  {
    "id": "ai-short-30",
    "titleKo": "소금등대 30",
    "textKo": "바다가 말라붙은 뒤에도 등대는 불을 밝혔다. 더 이상 배는 오지 않았고, 수평선 자리에는 하얀 소금 평원이 끝없이 펼쳐졌다. 등대지기 수연은 매일 밤 렌즈를 닦고 빛을 돌렸다. 마을 사람들은 전기가 아깝다며 그만두라고 했지만, 수연은 바다를 기억하는 누군가에게는 아직 신호가 필요할지 모른다고 말했다. 어느 겨울밤, 소금 평원 너머에서 작은 종소리가 들렸다. 수연이 불빛을 낮추자, 소금 결정에 반사된 빛이 길처럼 이어졌다. 그 길을 따라 온 것은 배가 아니라 낡은 항해 일지를 품은 아이였다. 아이는 할아버지가 남긴 지도를 따라 잃어버린 항구를 찾고 있었다. 수연은 등대가 더 이상 배를 부르지 못해도, 기억을 잃은 사람에게 방향을 줄 수 있다는 것을 깨달았다. 이 이야기는 30번째 연습문장으로, 천천히 끝까지 입력하며 쉼표와 마침표의 리듬을 느끼도록 구성되었다. 마지막 문장에 이르면 인물은 작지만 분명한 선택을 하고, 독자는 조용한 장면 하나를 마음에 남긴다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다. 다음 날에도 세계는 크게 달라지지 않았지만, 주인공은 어제보다 조금 덜 망설였다. 작은 친절과 오래된 약속은 느리게 움직여도 결국 누군가의 하루를 건너가게 만든다.",
    "titleEn": "Salt Lighthouse 30",
    "textEn": "After a quiet night, the town revealed a small impossible place that only patient people could notice. A tired traveler arrived with a question that did not fit any ordinary map, ticket, or schedule. Instead of giving a quick answer, the keeper of the place listened for the hidden wish inside the question. They searched old drawers, dim corridors, and memories left behind by strangers who had passed through before. By morning, nothing in the town looked dramatically changed, yet one person could finally take the next step without fear. The story ends quietly because not every miracle needs a trumpet; some miracles are only a door opening at the right moment. This is practice story 30, written with steady sentences for long-form typing practice. The road ahead remained uncertain, but the character carried a warmer kind of courage, the sort that grows from being seen, helped, and gently reminded that a small choice can still change the shape of a day. "
  }
];

export const koreanAiShortStoryPassages: PassageItem[] = bilingualAiShortStories.map((story) => ({
  title: story.titleKo,
  text: story.textKo,
  source: '자체 작성 / AI 보조 창작, 인간 검수',
}));

export const englishAiShortStoryPassages: PassageItem[] = bilingualAiShortStories.map((story) => ({
  title: story.titleEn,
  text: story.textEn,
  source: 'Original / AI-assisted fiction, human reviewed',
}));
